export default {
  erreur500: "Service indisponible, veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurUpload: "Une erreur est survenue lors de l'envoi du fichier. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",
  erreurDownload: "Une erreur est survenue lors de la récupération du fichier. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",
  erreurRCR: "Impossible de récupérer la liste des RCR. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",
  erreurListeTraitements: "Impossible de récupérer la liste des traitements. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",
  erreurListeExemp: "Impossible de récupérer la liste des exemplarisations. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",
  erreurDemande: "Impossible mettre à jour la demande. Veuillez réessayer ultérieurement. <br /> Si le problème persiste, merci de contacter l'assistance.",

  headersArchiveAdminModif: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Demande', value: 'num', width: '1%' },
    { text: 'Modification', value: 'dateModification', width: '1%' },
    { text: 'ILN', value: 'iln', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Zones', value: 'zoneSousZone', width: '1%' },
    { text: 'Traitement', value: 'traitement', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
  ],
  headersArchiveModif: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Demande', value: 'num', width: '1%' },
    { text: 'Modification', value: 'dateModification', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Zones', value: 'zoneSousZone', width: '1%' },
    { text: 'Traitement', value: 'traitement', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
  ],
  headerModifAdmin: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Demande', value: 'num', width: '1%' },
    { text: 'Modification', value: 'dateModification', width: '1%' },
    { text: 'ILN', value: 'iln', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Zones', value: 'zoneSousZone', width: '1%' },
    { text: 'Traitement', value: 'traitement', width: '1%' },
    { text: 'Statut', value: 'statut', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
    { text: '', value: 'delete', width: '1%' },
  ],
  headerModif: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Demande', value: 'num', width: '1%' },
    { text: 'Modification', value: 'dateModification', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Zones', value: 'zoneSousZone', width: '1%' },
    { text: 'Traitement', value: 'traitement', width: '1%' },
    { text: 'Statut', value: 'statut', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
    { text: '', value: 'delete', width: '1%' },
  ],
  headerExempAdmin: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Numéro de la Demande', value: 'num', width: '1%' },
    { text: 'Date de création de la demande', value: 'dateCreation', width: '1%' },
    { text: 'Date de dernière mise à jour de la Demande', value: 'dateModification', width: '1%' },
    { text: 'ILN', value: 'iln', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Index de recherche', value: 'indexRecherche', width: '1%' },
    { text: 'Type d\'exemplarisation', value: 'typeExemp', width: '1%' },
    { text: 'Etat de la demande', value: 'statut', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
    { text: '', value: 'delete', width: '1%' },
  ],
  headerExemp: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Numéro de la Demande', value: 'num', width: '1%' },
    { text: 'Date de création de la demande', value: 'dateCreation', width: '1%' },
    { text: 'Date de dernière mise à jour de la Demande', value: 'dateModification', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Index de recherche', value: 'indexRecherche', width: '1%' },
    { text: 'Type d\'exemplarisation', value: 'typeExemp', width: '1%' },
    { text: 'Etat de la demande', value: 'statut', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
    { text: '', value: 'delete', width: '1%' },
  ],
  headerExempArchiveAdmin: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Numéro de la Demande', value: 'num', width: '1%' },
    { text: 'Date de création de la demande', value: 'dateCreation', width: '1%' },
    { text: 'Date de dernière mise à jour de la Demande', value: 'dateModification', width: '1%' },
    { text: 'ILN', value: 'iln', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Index de recherche', value: 'indexRecherche', width: '1%' },
    { text: 'Type d\'exemplarisation', value: 'typeExemp', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
  ],
  headerExempArchive: [
    { text: ' ', value: 'expand', width: '1%' },
    { text: 'Numéro de la Demande', value: 'num', width: '1%' },
    { text: 'Date de création de la demande', value: 'dateCreation', width: '1%' },
    { text: 'Date de dernière mise à jour de la Demande', value: 'dateModification', width: '1%' },
    { text: 'RCR', value: 'rcr', width: '1%' },
    { text: 'Index de recherche', value: 'indexRecherche', width: '1%' },
    { text: 'Type d\'exemplarisation', value: 'typeExemp', width: '1%' },
    { text: 'Résultat', value: 'codeStatut', width: '1%' },
  ],
};
