export default {
  erreur500: "Le service est indisponible. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurUpload: "Une erreur est survenue lors de l'envoi du fichier. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurDownload: "Une erreur est survenue lors de la récupération du fichier. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurRCR: "Il est impossible d'afficher la liste des RCR. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurListeTraitements: "Impossible de récupérer la liste des traitements. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurTypeExemp: "Le tri par type d’exemplarisation est impossible. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurListeExemp: "Il est Impossible de récupérer la liste des exemplarisations. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",
  erreurDemande: "Impossible mettre à jour la demande. Veuillez réessayer ultérieurement. Si le problème persiste, merci de contacter l'assistance.",

  headersArchiveAdminModif: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '11%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'ILN', value: 'iln', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Zones et sous-zones', value: 'zoneSousZone', width: '10%' },
    { text: 'Traitement', value: 'traitement', width: '20%' },
    { text: 'Statut', value: 'codeStatut', width: '7%' },
    { text: 'Téléchargement', value: '', width: '12%' },
  ],
  headersArchiveModif: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '15%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'RCR', value: 'rcr', width: '15%' },
    { text: 'Zones et sous-zones', value: 'zoneSousZone', width: '11%' },
    { text: 'Traitement', value: 'traitement', width: '20%' },
    { text: 'Statut', value: 'codeStatut', width: '7%' },
    { text: 'Téléchargement', value: '', width: '12%' },
  ],
  headerModifAdmin: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'ILN', value: 'iln', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Zones et sous-zones', value: 'zoneSousZone', width: '15%' },
    { text: 'Traitement', value: 'traitement', width: '15%' },
    { text: 'Statut', value: 'statut', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '8%' },
    { text: '', value: 'delete', width: '3%' },
  ],
  headerModif: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'RCR', value: 'rcr', width: '5%' },
    { text: 'Zones et sous-zones', value: 'zoneSousZone', width: '15%' },
    { text: 'Traitement', value: 'traitement', width: '25%' },
    { text: 'Statut', value: 'statut', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '10%' },
    { text: '', value: 'delete', width: '3%' },
  ],
  headerExempAdmin: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '10%' },
    { text: 'ILN', value: 'iln', width: '7%' },
    { text: 'RCR', value: 'rcr', width: '8%' },
    { text: 'Type', value: 'typeExemp', width: '17%' },
    { text: 'Index', value: 'indexRecherche', width: '8%' },
    { text: 'Statut', value: 'statut', width: '14%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '8%' },
    { text: '', value: 'delete', width: '3%' },
  ],
  headerExemp: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Type', value: 'typeExemp', width: '15%' },
    { text: 'Index', value: 'indexRecherche', width: '10%' },
    { text: 'Statut', value: 'statut', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '8%' },
    { text: '', value: 'delete', width: '3%' },
  ],
  headerExempArchiveAdmin: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '15%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'ILN', value: 'iln', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Type', value: 'typeExemp', width: '15%' },
    { text: 'Index', value: 'indexRecherche', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '10%' },
  ],
  headerExempArchive: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '15%' },
    { text: 'Création', value: 'dateCreation', width: '15%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Type', value: 'typeExemp', width: '15%' },
    { text: 'Index', value: 'indexRecherche', width: '15%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '10%' },
  ],
  headerRecouvAdmin: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '10%' },
    { text: 'ILN', value: 'iln', width: '7%' },
    { text: 'RCR', value: 'rcr', width: '8%' },
    { text: 'Index', value: 'indexRecherche', width: '10%' },
    { text: 'Statut', value: 'statut', width: '15%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '5%' },
    { text: '', value: 'delete', width: '10%' },
  ],
  headerRecouv: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '10%' },
    { text: 'Modification', value: 'dateModification', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Index', value: 'indexRecherche', width: '10%' },
    { text: 'Statut', value: 'statut', width: '15%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '5%' },
    { text: '', value: 'delete', width: '10%' },
  ],
  headerRecouvArchiveAdmin: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '10%' },
    { text: 'Création', value: 'dateCreation', width: '15%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'ILN', value: 'iln', width: '10%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Index', value: 'indexRecherche', width: '10%' },
    { text: 'Statut', value: 'codeStatut', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '10%' },
  ],
  headerRecouvArchive: [
    { text: '', value: 'expand', width: '5%' },
    { text: 'Demande', value: 'num', width: '15%' },
    { text: 'Création', value: 'dateCreation', width: '15%' },
    { text: 'Modification', value: 'dateModification', width: '15%' },
    { text: 'RCR', value: 'rcr', width: '10%' },
    { text: 'Index', value: 'indexRecherche', width: '15%' },
    { text: 'Statut', value: 'codeStatut', width: '10%' },
    { text: 'Téléchargement', value: 'codeStatut', width: '10%' },
  ],
};
